version: '3.9'

services:
  db:
    image: mysql:8
    container_name: ecommerce_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --innodb-buffer-pool-size=128M
      --innodb-log-file-size=64M

  web:
    build: .
    container_name: ecommerce_backend
    command: gunicorn app.wsgi:application --workers 1 --threads 2 --bind 0.0.0.0:8000
    volumes:
      - ./project-pao:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data: